### PR TITLE
[DAEMON-200] Wait for data before parsing

### PR DESCRIPTION
**Pull request by garymathews**
- Include the fixes from TIMOB-24906
- Wait for any response data before parsing device list

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24906)

### CODE REVIEW

**Comment by cb1kenobi** [comment]
I’m not sure I am going to accept this. We have not seen this problem in androidlib. TiSDK does not use androidlib. Perhaps you meant to fix this in node-titanium-sdk?

**Comment by garymathews** [comment]
The fixes are already in node-titanium-sdk, I decided to port them over since I believe the same issue would occur here.

**Comment by cb1kenobi** [comment]
1) The code in androidlib is not based on the code in node-titanium-sdk. It's pulled from the old titanium-sdk directory in titanium_mobile almost 2 years ago. I applied this fix over a year ago to androidlib's code which was recently cleaned up again.

2) You have not provided any unit tests or steps to reproduce that androidlib suffers from the same problem that node-titanium-sdk did.

So, unless you can prove that the current androidlib has an issue and that this PR fixes it, I will have to close this PR. I do appreciate you going above and beyond to port your fix.

**Comment by garymathews** [comment]
@cb1kenobi This is a valid issue, try plugging and un-plugging and device a few times or start and close an emulator a few times. It's temperamental, but sometimes the device is not detected. Instead this is logged:
```
appcd:plugin:host:74372 > androidlib:connection [1] [DO_NOTHING] [host:track-devices] Received 51 bytes
```
But obtaining device information yields nothing:
```
appc appcd exec /android/latest/info/devices
[]
```

**Comment by garymathews** [comment]
@cb1kenobi I believe this is the issue @ssekhri ran into [DAEMON-200](https://jira.appcelerator.org/browse/DAEMON-200)

**Comment by cb1kenobi** [comment]
@garymathews If you take the daemon out of the equation, you can run `SNOOPLOGG=* node bin/androidlib track-devices` directly from androidlib and watch the events. I will attempt to reproduce given your test case above. Stay tuned.

**Pull request merged**
